base/urls.py
from django.urls import path
from . import views

app_name='base'

urlpatterns = [
	path('', views.home , name='home'),
    path('contact/', views.contact , name='contact'),

    # projects urls

#   - ai-Workflow
    path('ai-Workflow/', views.aiWorkflow , name='ai-Workflow'),
#   - learn-hub
    path('learn-hub/', views.learnhub , name='learn-hub'),
#   - job-boards
    path('job-boards/', views.jobboards , name='job-boards'),
#   - cars-marketplace
    path('cars-marketplace/', views.carsmarketplace , name='cars-marketplace'),
#   - chat-app
    path('chat-app/', views.chatapp , name='chat-app'),
#   - e-commerce
    path('e-commerce/', views.ecommerce , name='e-commerce'),
#   - mario 
    path('mario/', views.mario , name='mario'),
#   - networks
    path('networks/', views.networks , name='networks'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls' , namespace='base')) ,
]

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    subject = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}), required=True)

base/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import messages
from .forms import ContactForm

# Create your views here.


def home(request):
	return render(request, 'base/home.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            send_mail(
                f"New Contact: {subject}",
                f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}",
                'ahmdmadbdallhmhmd@gmail.com',  # email that send mails
                ['anaahmed1512@gmail.com'],  # my receiver email that receive mails
                fail_silently=False,
            )
            messages.success(request, 'Your message has been sent successfully!')
            return redirect('base:contact')
    else:
        form = ContactForm()
    return render(request, 'base/contact.html', {'form': form})


##############################################################################################

#   - ai-Workflow
def aiWorkflow(request):
	return render(request, 'base/ai-Workflow.html')

#   - learn-hub
def learnhub(request):
	return render(request, 'base/learn-hub.html')

#   - job-boards
def jobboards(request):
	return render(request, 'base/job-boards.html')

#   - cars-marketplace
def carsmarketplace(request):
	return render(request, 'base/cars-marketplace.html')

#   - chat-app
def chatapp(request):
	return render(request, 'base/chat-app.html')

#   - e-commerce
def ecommerce(request):
	return render(request, 'base/e-commerce.html')

#   - mario 
def mario(request):
	return render(request, 'base/mario.html')

#   - networks
def networks(request):
	return render(request, 'base/networks.html')

base/templates/base/ai-Workflow.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>


<div class="container">
    <h2>AI Workflow Platform</h2>
    <h2><strong>AI Workflow Platform</strong></h2>

<ul>
  <li><strong>Platform Purpose:</strong> Contributed to a visual AI development platform where users can build complete AI models by connecting modular nodes (each representing an AI model or data operation) without writing code.</li>
  <br>
  <li><strong>Backend Architecture:</strong> Used Controller–Service–Repository architecture for a clean and scalable backend structure, with workflows running in the backend and returning results to users.</li>
  <br>
  <li><strong>Repository Layer:</strong> Focused on the Repository layer, implementing saving, loading, updating, and deleting node data, with file-based storage and database integration.</li>
  <br>
  <li><strong>Chatbot API:</strong> Built the chatbot API using Django Channels, enabling real-time interactions between users and the AI engine.</li>
  <br>
  <li><strong>Web Platform:</strong> Worked on the web platform allowing users to access tutorials, share projects, and browse community projects.</li>
  <br>
  <li><strong>Authentication & Authorization:</strong> Implemented authentication and authorization, including login, OTP-based password reset, and role-based access.</li>
  <br>
  <li><strong>Real-Time Collaboration:</strong> Enabled real-time chat rooms where messages are stored in the database, and users can collaborate in project-specific rooms.</li>
</ul>

    <h4>Technologies Used</h4>

    <a href="https://github.com/MoNafea01/AI-NO" class="btn btn-dark" target="_blank">View on GitHub</a>
</div>
<br>
</body>
</html>

base/templates/base/cars-marketplace.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>


<div class="container">
    <h2>Car Marketplace</h2>
    <iframe width="100%" height="400" src="https://www.youtube.com/embed/RsOQAPnC5Vs" frameborder="0" allowfullscreen></iframe>

<ul>
  <li><strong>Project Type:</strong> Django-based web application</li>
  <br>
  <li><strong>Main Features:</strong> Manage user profiles, car listings, and locations</li>
  <br>
  <li><strong>Functionality:</strong>
    <br>
    <ul>
      <li>User registration and profile management</li>
      <br>
      <li>Create, post, filter, and like car listings</li>
      <br>
    </ul>
  </li>
  <br>
  <li><strong>Implementation:</strong>
    <br>
    <ul>
      <li>Used models, forms, and signals</li>
      <br>
      <li>Integrated custom widgets</li>
      <br>
      <li>Optimized data flow with Django signals</li>
      <br>
    </ul>
  </li>
  <br>
  <li><strong>Goal:</strong> Seamless and interactive user experience in the marketplace</li>
</ul>

    <h4>Technologies Used</h4>
    
<ul>
  <li><strong>Framework:</strong> Django</li>
  <br>
  <li><strong>Architecture:</strong> MVT (Model-View-Template)</li>
  <br>
  <li><strong>Authentication:</strong> Django built-in authentication system</li>
  <br>
  <li><strong>Features:</strong> Django models, forms, signals, and custom widgets</li>
  <br>
  <li><strong>Interactivity:</strong> Django signals for real-time behavior and data flow</li>
  <br>
  <li><strong>Frontend:</strong> HTML, CSS and Bootstrap</li>
  <br>
  <li><strong>Database:</strong> SQLite3</li>
</ul>
    <a href="https://github.com/mellooz/AutoMax" class="btn btn-dark" target="_blank">View on GitHub</a>
</div>
<br>
</body>
</html>

base/templates/base/chat-app.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>


<div class="container">
    <h2>Chat App</h2>
    <iframe width="100%" height="400" src="https://www.youtube.com/embed/N2demNQKuls" frameborder="0" allowfullscreen></iframe>
    <ul>
        <li><strong>Framework:</strong> Django and Django Channels</li>
        <br>
        <li><strong>Communication:</strong> WebSockets for instant communication</li>
        <br>
        <li><strong>Event Handling:</strong> AsyncWebsocketConsumer for handling events</li>
        <br>
        <li><strong>Real-Time Interaction:</strong> Real-time message exchange between users in the same room</li>
        <br>
        <li><strong>Technology:</strong> Channel Layers for facilitating interactive communication</li>
    </ul>
    <h4>Technologies Used</h4>
    <ul>
        <li><strong>Backend Framework:</strong> Django</li>
        <br>
        <li><strong>Real-Time Communication:</strong> Django Channels, WebSockets</li>
        <br>
        <li><strong>Event Handling:</strong> AsyncWebsocketConsumer</li>
        <br>
        <li><strong>Real-Time Interaction:</strong> Channel Layers (using in-memory backend)</li>
        <br>
        <li><strong>Frontend:</strong> JavaScript, HTML, CSS (for the chat UI)</li>
    </ul>
    <a href="https://github.com/mellooz/ChatApp" class="btn btn-dark" target="_blank">View on GitHub</a>
</div>
<br>
</body>
</html>

base/templates/base/contact.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>

	<!-- ################################################################### -->

    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg rounded-3">
                <div class="card-body">
                    <h2 class="text-center mb-4">Contact Me</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_name" class="form-label fw-bold">Name</label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label fw-bold">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="mb-3">
                            <label for="id_subject" class="form-label fw-bold">Subject</label>
                            {{ form.subject }}
                        </div>
                        <div class="mb-3">
                            <label for="id_message" class="form-label fw-bold">Message</label>
                            {{ form.message }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary w-50">Send</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


</body>
</html>

base/templates/base/e-commerce.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>


<div class="container">
    <h2>E-Commerce Platform</h2>
    <iframe width="100%" height="400" src="https://www.youtube.com/embed/GQCqNxYShUc" frameborder="0" allowfullscreen></iframe>
    <ul>
        <li><strong>Framework:</strong> Django</li>
        <br>
        <li><strong>Features:</strong>
            <br>
          <ul>
            <li>Dynamic product listings</li>
            <br>
            <li>Shopping cart</li>
            <br>
            <li>Checkout process</li>
          </ul>
        </li>
        <br>
        <li><strong>Order Management:</strong> Efficiently handles product inventory, customer data, and shipping details</li>
        <br>
        <li><strong>User Authentication:</strong> Secure login and registration for users</li>
        <br>
        <li><strong>Payment Integration:</strong> PayPal for payment processing</li>
        <br>
        <li><strong>Data Models:</strong> Designed relational models and views for inventory and customer data</li>
    </ul>
    <h4>Technologies Used</h4>
    <ul>
        <li><strong>Backend Framework:</strong> Django</li>
        <br>
        <li><strong>Authentication:</strong> Django built-in authentication system</li>
        <br>
        <li><strong>Payment Integration:</strong> PayPal API</li>
        <li><strong>Frontend:</strong> HTML, CSS, JavaScript, Bootstrap</li>
        <br>
        <li><strong>Database:</strong> SQLite3</li>
        <br>
        <li><strong>Models:</strong> Django relational models for product inventory and customer data</li>
        <br>
        <li><strong>Order Management:</strong> Custom views and logic for managing orders and shipping details</li>
    </ul>
    <a href="https://github.com/mellooz/E-Commerce" class="btn btn-dark" target="_blank">View on GitHub</a>
</div>
<br>
</body>
</html>

base/templates/base/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
	<br>
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="card card-body h-100  border-info" id="profile-wrapper">
					<img id="profile-pic" src="{% static 'images/ahmed.jpg' %}" >
					<hr>
					<h4>Ahmed Emad</h4>
					<p>Cybersecurity Engineer | Red Teaming | Backend Developer</p>
				</div>
			</div>

			<div class="col-md-9">
				<div class="card card-body h-100  border-info">
					<h4>About Me</h4>
					<hr>
					<p>I’m a passionate <strong>Cybersecurity Engineer</strong> specializing in <strong>Red Teaming</strong>, with a strong background in <strong>backend development using Django</strong>. I thrive on identifying vulnerabilities, enhancing security defenses, and building robust backend systems.</p>

					<p>My expertise bridges <strong>offensive security</strong> and <strong>software development</strong>, allowing me to create secure and scalable applications. Always eager to learn and explore new technologies, I enjoy solving complex challenges and staying ahead in the ever-evolving tech landscape.</p>

					<ul class="social-links">
						<li><a href="https://www.linkedin.com/in/ahmed0emad/" target="_blank"><img class="social" src="{% static 'images/linkedin.png' %}"></a></li>
						<li><a href="https://github.com/mellooz" target="_blank"><img class="social" src="{% static 'images/github.png' %}"></a></li>
						<li><a href="mailto:anaahmed1512@gmail.com" target="_blank"><img class="social" src="{% static 'images/gmail.png' %}"></a></li>
						<li><a href="https://wa.me/+201092247661" target="_blank"><img class="social" src="{% static 'images/whatsapp.png' %}"></a></li>
						<li><a href="#" download target="_blank"><img class="social" src="{% static 'images/cv.png' %}"></a></li>
					</ul>
				</div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-6">
				<div class="card card-body h-100">
					<h5>Education</h5>
					<hr>
					<p><strong>Bachelor’s Degree in Computer Engineering</strong></p>
					<p><strong>University:</strong> Zagazig University, Egypt</p>
					<p><strong>Expected Graduation:</strong> July 2025</p>
					</div>
			</div>

			<div class="col-md-6">
				<div class="card card-body h-100">
					<h5>Student Activities</h5>
					<hr>
					<p><strong>IEEE Zagazig Student Branch</strong> – Ambassador & Member (June 2022 – July 2023)</p>
					<p><strong>AIESEC Zagazig</strong> – Team Leader OGV (August 2022 – January 2023)</p>
					</ul>
				</div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-6">
				<div class="card card-body h-100">
					<h5>Skills & Courses</h5>
					<hr>
					<h6>Programming Languages:</h6>
                        <p>Python, Java, C, Bash, JavaScript, HTML, CSS</p>
					<h6>Tools & Technologies:</h6>
                        <p>Docker, Git, GitHub, Postman, Burp Suite, SQLmap, Nmap, VirtualBox, Wireshark, Cisco Packet Tracer</p>
					<h6>Databases:</h6>
						<p>MySQL, PostgreSQL, MongoDB</p>
					<h6>Courses:</h6>
						<p>eJPT v1, Security+, Red Hat Admin 1, OWASP Top 10, CCNA</p>
					<h6>Frameworks & Architectures:</h6>
						<p>Django (MVT & REST API), JavaFX</p>
					<h6>Languages:</h6>
						<p>English (B2), German (B1.1) - Working towards C1</p>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card card-body h-100">
					<h5>Work Experience</h5>
				<hr>
				<p><strong>IT Assistant (Part-Time)</strong></p>
				<p><strong>Abdeldayem Group</strong> | July 2023 – February 2024</p>
				<ul>
					<li>Assisted in building and maintaining the group's network infrastructure.</li>
					<li>Automated workflows using Google Apps Script.</li>
					<li>Supported hardware and software troubleshooting.</li>
				</ul>
				</div>
			</div>
		</div>
		<br>

		<div class="row">
			<div class="col-md-12">
				<div class="card card-body h-100">
					<h5>Projects</h5>
					<hr>
					<ul>
						<li><a class="nav-link" href="{% url 'base:ai-Workflow' %}"><strong>AI Workflow Platform</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:learn-hub' %}"><strong>LearnHub</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:job-boards' %}"><strong>Job Boards Website</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:cars-marketplace' %}"><strong>Car Marketplace</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:chat-app' %}"><strong>Chat App</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:e-commerce' %}"><strong>E-commerce Platform</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:mario' %}"><strong>Mario Game</strong></a></li>
						<br>
						<li><a class="nav-link" href="{% url 'base:networks' %}"><strong>Networking Projects (RIP, OSPF, VLAN)</strong></a></li>
					</ul>
			</div>
		</div>
		<br>
	</div>

</body>
</html>

base/templates/base/job-boards.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>


<div class="container">
    <h2>Job Boards Website</h2>
    <iframe width="100%" height="400" src="https://www.youtube.com/embed/XG8pJtOk7O8" frameborder="0" allowfullscreen></iframe>
    <br>
    <p>
        <strong>A Django-based job portal</strong> using the <strong>MVT architecture</strong>. The platform allows users to:
      </p>
      <ul>
        <li><strong>Sign up</strong>, <strong>log in</strong>, and <strong>manage their profiles</strong></li>
        <br>
        <li><strong>Employers</strong> can post jobs with details such as:
          <ul>
            <li><strong>  - Title</strong></li>
            <br>
            <li><strong>  - Location</strong></li>
            <br>
            <li><strong>  - Salary</strong></li>
            <br>
            <li><strong>  - Job type</strong></li>
            <br>
          </ul>
        </li>
        <br>
        <li><strong>Applicants</strong> can apply directly through the platform</li>
        <br>
        <li>Includes <strong>job filtering</strong> for better user experience</li>
        <br>
        <li>Has a <strong>blog section</strong> with <strong>comments</strong> and <strong>search functionality</strong></li>
        <br>
        <li>Features a <strong>contact page</strong> with <em>email support</em></li>
        <br>
      </ul>
      
      <p>
        Built using <code>Django</code>'s built-in <strong>authentication</strong>, <strong>class-based models</strong>, and <strong>template system</strong>.
      </p>
    <h4>Technologies Used</h4>
    <ul>
        <li><strong>Backend Framework:</strong> Django</li>
        <br>
        <li><strong>Architecture:</strong> MVT (Model-View-Template)</li>
        <br>
        <li><strong>Authentication:</strong> Django built-in authentication</li>
        <br>
        <li><strong>Templating:</strong> Django template engine</li>
        <br>
        <li><strong>Models:</strong> Class-based models</li>
        <br>
        <li><strong>Database:</strong> SQLite3</li>
        <br>
        <li><strong>Support:</strong> Email support for contact and communication</li>
        <br>
      </ul>
    <a href="https://github.com/mellooz/Job-Boards" class="btn btn-dark" target="_blank">View on GitHub</a>
</div>
<br>

</body>
</html>

base/templates/base/learn-hub.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Ahmed Emad</title>
	<link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>
<body>
	<!-- ################################################################### -->

	    {% include 'base/navbar.html' %}

	<!-- ################################################################### -->
<br>


<div class="container">
    <h2>LearnHub</h2>
    <br>
    <p>
        <strong>LearnHub API</strong> is a backend service built with <strong>Django</strong> and designed to support an <strong>e-learning platform</strong> with
        <strong>JWT</strong> and <strong>OTP-based authentication</strong>.
      </p>
      <p>
        Users can:
        <ul>
          <li><strong>Enroll</strong> in courses</li>
          <li><strong>Search</strong> for content</li>
          <li><strong>Create</strong> and <strong>manage</strong> their own courses with lessons</li>
          <li><strong>Track</strong> their activity via a personalized profile</li>
        </ul>
      </p>
      <p>
        The system ensures <strong>secure account verification</strong> and <strong>password reset</strong> through <em>email-based OTPs</em>.
      </p>
    <h4>Technologies Used</h4>
    <ul>
        <li><strong>Backend Framework:</strong> <code>Django</code></li>
        <li><strong>API Format:</strong> <code>REST API</code></li>
        <li><strong>Authentication:</strong> <code>JWT</code>, <code>OTP (Email-based)</code></li>
        <li><strong>Database:</strong> <code>Sqlite3</code></li>
        <li><strong>Email Services:</strong> <code>SMTP</code> for OTP verification and password reset</li>
      </ul>
    <a href="https://github.com/mellooz/LearnHub" class="btn btn-dark" target="_blank">View on GitHub</a>
</div>

</body>
</html>

base/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-info">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base:home' %}">My Portfolio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:contact' %}">Contact Me</a>
          </li>
        </ul>
      </div>
    </div>
</nav>